#!/usr/bin/env python3
"""Generate the YAM camera-rig embodiments (observer 24-view ring).

Reuses the ring geometry from gen_aloha_rigs.py verbatim -- the ring is
anchored to the scene (official observer camera revolved around the table
target), not to the robot, so the camera entries are identical to the aloha
rigs and the two datasets share the exact 24-view index contract:
index 0..20 -> az -150..+150 step 15; 21 = +165, 22 = -165, 23 = 180;
third_view_16 = the official observer camera.

    yam-mv2   head_camera + observer ring (third_view_0..23)   collection

Each rig directory holds a generated config.yml plus relative symlinks into
../yam/ for everything else, and a real .gitattributes (symlinked ones are
ignored by git) opting out of the parent directory's LFS rules.
Rerun after editing; `--check` verifies the files on disk.
"""
import os
import sys

import yaml

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from gen_aloha_rigs import ring_camera, EMBODIMENTS, ALL  # noqa: E402

STOCK = "yam"
RIGS = {
    "mv2": (["head_camera"], [("obs", "third_view", ALL)]),
}
GITATTRIBUTES = """\
# assets/embodiments/.gitattributes routes *.yml through Git LFS; GitHub
# refuses new LFS objects on public forks. `!` resets to unspecified (default
# text handling); `-` would force binary diffs. Same opt-out as ../yam/.
* !filter !diff !merge !text
"""


def build(rig):
    stock_cfg = yaml.safe_load(open(os.path.join(EMBODIMENTS, STOCK, "config.yml")))
    base_names, rings = RIGS[rig]
    stock_cams = {c["name"]: c for c in stock_cfg["static_camera_list"]}
    cams = [stock_cams[n] for n in base_names]
    for ring, prefix, indices in rings:
        cams += [ring_camera(ring, prefix, i) for i in indices]
    cfg = dict(stock_cfg)
    cfg["static_camera_list"] = cams
    header = f"# Generated by script/gen_yam_rigs.py (rig: {rig}) -- do not edit by hand.\n"
    return header + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True,
                                   default_flow_style=None, width=100)


def main():
    check = "--check" in sys.argv
    stale = []
    for rig in RIGS:
        rig_dir = os.path.join(EMBODIMENTS, f"{STOCK}-{rig}")
        os.makedirs(rig_dir, exist_ok=True)
        for name, content in (("config.yml", build(rig)), (".gitattributes", GITATTRIBUTES)):
            path = os.path.join(rig_dir, name)
            old = open(path).read() if os.path.exists(path) else None
            if old != content:
                if check:
                    stale.append(path)
                else:
                    open(path, "w").write(content)
                    print(f"wrote {path}")
        for entry in sorted(os.listdir(os.path.join(EMBODIMENTS, STOCK))):
            if entry in ("config.yml", ".gitattributes"):
                continue
            link = os.path.join(rig_dir, entry)
            if os.path.lexists(link):
                continue
            os.symlink(os.path.join("..", STOCK, entry), link)
            print(f"link  {link} -> ../{STOCK}/{entry}")
    if check and stale:
        raise SystemExit("stale: " + " ".join(stale))
    if check:
        print("ok: files on disk match the spec")


if __name__ == "__main__":
    main()
